#!/usr/bin/env bash
wget --content-disposition -v "https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=es-ES"
tar -xjf firefox-*.tar.bz2
sudo rm -r /opt/firefox
sudo mv firefox /opt
rm firefox-*.tar.bz2